---
title: "Clean_script"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###Loading the data:
```{r}
#counlist=read.table(file='Countries.txt',header = T,sep='\t',stringsAsFactors = F)
counlist=read.table(file='Country_updated.csv',header = T,sep='\t',stringsAsFactors = F)#Updated outbreak list(https://link.springer.com/article/10.1007%2Fs11908-019-0675-8)


totaln=tapply(counlist$n,counlist$Country,sum)#calculate number of isolates (cases) per country

outot=data.frame(names(totaln),totaln,row.names = NULL)
colnames(outot)=c('Country','Total_isolates')

outot$n_outbreaks=as.numeric(table(counlist$Country))#Calculate number of outbreak per country

coord_unique=subset(counlist,!duplicated(counlist$Country),select = c("Country","lat","lon"))

outot=merge(outot,coord_unique,by='Country')
```

###Mapping:
####Without points:
```{r}
#install.packages("mapproj")
#install.packages('maps')
library(ggplot2)
library(dplyr)
library(maps)
library(mapproj)
WorldData <- map_data('world')
WorldData %>% filter(region != "Antarctica") -> WorldData
WorldData <- fortify(WorldData)

p <- ggplot()
p <- p + geom_map(data=WorldData, map=WorldData,
                  aes(x=long, y=lat, group=group, map_id=region),
                  fill="white", colour="#7f7f7f", size=0.5)
p <- p + geom_map(data=outot, map=WorldData,
                  aes(fill=Total_isolates, map_id=Country),
                  colour="#7f7f7f", size=0.5)
p <- p + coord_map("rectangular", lat0=0, xlim=c(-180,180), ylim=c(-60, 90))
p <- p + scale_y_continuous(breaks=c())
p <- p + scale_x_continuous(breaks=c())
p <- p + theme_bw()
p <- p + theme(panel.border = element_blank())
p <- p + scale_fill_gradient(low="thistle2",high="darkred",breaks=c(1,10,100,200,max(counlist$n)),trans='log10')
p
```
####With the number of outbreaks:
```{r}
p1=p + geom_point(data=outot,aes(x=lon,y=lat,size=n_outbreaks),alpha=0.5,stroke=1.2)
p1 <- p + labs(size='Number of outbreaks',fill="Number of total isolates", title="", x="", y="")
p1
```
###Other way of plotting the world map:
```{r}
world_map <- map_data("world")
world_map %>% filter(region != "Antarctica")->world_map
world_map=fortify(world_map)

p <- ggplot() + coord_fixed() +
  xlab("") + ylab("")
base_world_messy <- p + geom_polygon(data=world_map, aes(x=long, y=lat, group=group), 
                                     colour="#7f7f7f", fill="white")
base_world_messy
cleanup <- 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "white"),
        axis.ticks=element_blank(), axis.text.x=element_blank(),
        axis.text.y=element_blank())
base_world=base_world_messy+cleanup
base_world
```
###Colouring per outbreak:
```{r}
colour_per_outreak=base_world+ggtitle('')+geom_jitter(data=counlist,position=position_jitter(width=1.4, height=1.4),aes(x=lon, y=lat, color=Year,size=n),alpha=0.6,stroke=0.9)+labs(colour='Outbreak years')+theme(legend.title = element_text(size = 15),legend.text =element_text(size = 14) )+scale_size_continuous(range = c(5,17),breaks = c(min(counlist$n),mean(counlist$n),max(counlist$n)))
colour_per_outreak
```


###Saving:
```{r}
ggsave(filename ='map.pdf',plot=colour_per_outreak,height = 17,width = 17)
```





