---
title: "Range plots"
author: "Léonard Jequier"
date: "21 novembre 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Data
```{r}
mic = read.csv("MIC2.csv", header = T, sep = ";")
names(mic)[1] = "Country"
summary(mic)
```
### rearrenge data by date:
```{r}
mic$epi = paste( mic$Year, mic$Country, sep = "_")
mic = mic[order(mic$epi),]
mic$row = seq(1:length(mic$Country))


mic = mic[seq(1, length(mic$Country)-2),]
```

### Fluco - Deal with missing data
```{r}
mic$FL_min = log2(mic$FL_min)
mic$FL_max = log2(mic$FL_max)

for(i in seq(1:length(mic$Country))){
  if(!is.na(mic$FL_min[i]) & mic$FL_min[i] == mic$FL_max[i]) {
    mic$FL_min[i] = mic$FL_min[i] -0.25
    mic$FL_max[i] = mic$FL_max[i] +0.25
}
}


```

### Fluconazole - plot
```{r}
library("ggplot2")

#xlab = c(expression(frac(1,32)), expression(frac(1,16)), expression(frac(1,8)),  expression(frac(1,4)), expression(frac(1,2)), 2 ** seq(0,8))
xlab = 2 ** seq(-4,8)
length(xlab)
length(seq(-5,8))
#breakpoint glabrata = 32
png('fluco_same.png',height = 550 , width = 500)
par(mar=c(3,2,2,2))

pf = ggplot(mic) 

pf = pf +  geom_segment(aes(x=FL_min, 
                          y = row , xend=FL_max ,
                          yend = row),
                        show.legend = F,
                        size = 2,
                      colour = "cornflowerblue") 

pf2 = pf + scale_y_continuous(name = "",breaks = 1:length(mic$n) ,labels = as.character(mic$epi)) 

pf3 = pf2 + scale_x_continuous(name = "MIC (mg/L)",limits = c(-4.5, 8.5), breaks = seq(-4, 8), labels = xlab)

pf3 = pf3 + geom_vline(xintercept= (log2(32)), colour = "red", linetype = "dashed")
pf3 = pf3 + coord_fixed(0.8)
subt = expression(paste("with breakpoint for ", italic("C.glabrata")))
pf3 = pf3 + labs(title = "Fluconazole", subtitle = subt)
pf3 = pf3 + theme(plot.margin = unit(c(0.5,0.25,0.5,0.5), "cm"),
                  plot.title = element_text(hjust = 0, size = 30),
                  plot.subtitle=element_text(size=20, hjust=0,
                                            color="red"), 
                  axis.text.y = element_text(size = 15, face = "bold"), 
                  axis.title.x = element_text(size = 20, face = "bold"),
                  axis.text.x = element_text(size = 15, angle = 45, hjust = 1, face = "bold"))

print(pf3)

dev.off()
```

### Casp - deal with NA
```{r}
mic$Casp_min = as.numeric(mic$Casp_min)
mic$Casp_max = as.numeric(mic$Casp_max)

mic$Casp_min = log2(mic$Casp_min)
mic$Casp_max = log2(mic$Casp_max)

mic$Casp_min == mic$Casp_max

for(i in seq(1:length(mic$Country))){
  if(!is.na(mic$Casp_min[i] == mic$Casp_max[i]) & mic$Casp_min[i] == mic$Casp_max[i]) {
    mic$Casp_min[i] = mic$Casp_min[i] -0.05
    mic$Casp_max[i] = mic$Casp_max[i] +0.05
}
}
```

### Caspo - plot 
```{r}

png('Caspo_same.png',height = 550 , width = 500)

pc = ggplot(mic) 

pc = pc +  geom_segment(aes(x=Casp_min, 
                          y = row , xend=Casp_max ,
                          yend = row),
                          size = 2,
                        show.legend = F,
                      colour = "cornflowerblue") 

pc2 = pc + scale_y_continuous(name = "", breaks = 1:length(mic$n) ,labels = rep(c(""), times = length(mic$n))) 

pc3 = pc2 + scale_x_continuous(name = "MIC (mg/L)",limits = c(-4.5, 8.5), breaks = seq(-4, 8), labels = xlab)

pc3 = pc3 + geom_vline(xintercept= (log2(0.064)), colour = "red", linetype = "dashed") 
  
pc3 = pc3 + coord_fixed(0.8)
subt = expression(paste("with Anidafungin breakpoint for ", italic("C.glabrata")))
pc3 = pc3 + labs(title = "Caspofungin", subtitle = subt)
pc3 = pc3 + theme(plot.margin = unit(c(0.5,0.25,0.5,0.5), "cm"),
                  plot.title = element_text(hjust = 0, size = 30),
                  plot.subtitle=element_text(size=20, hjust=0,
                                            color="red"), 
                  axis.text.y = element_text(size = 15, face = "bold"), 
                  axis.title.x = element_text(size = 20, face = "bold"),
                  axis.text.x = element_text(angle = 45, hjust = 1, size = 15, face = "bold"))


print(pc3)

dev.off()
```

### AMB - deal with NA
```{r}
mic$AMB_min = as.numeric(mic$AMB_min)
mic$AMB_max = as.numeric(mic$AMB_max)

mic$AMB_min = log2(mic$AMB_min)
mic$AMB_max = log2(mic$AMB_max)

mic$AMB_min == mic$AMB_max

for(i in seq(1:length(mic$Country))){
  if(!is.na(mic$AMB_min[i] == mic$AMB_max[i]) & mic$AMB_min[i] == mic$AMB_max[i]) {
    mic$AMB_min[i] = mic$AMB_min[i] -0.05
    mic$AMB_max[i] = mic$AMB_max[i] +0.05
}
}
```

### AMB - plot 
```{r}
#breakpoint glabrata = 1

png('AMB_same.png',height = 550 , width = 500)
par(mar=c(3,2,2,2))

pa = ggplot(mic) 

pa = pa +  geom_segment(aes(x=AMB_min, 
                          y = row , xend=AMB_max ,
                          yend = row),
                           size = 2,
                        show.legend = F,
                      colour = "cornflowerblue") 

pa2 = pa + scale_y_continuous(name = "",breaks = 1:length(mic$n) ,labels = as.character(mic$epi)) 
pa3 = pa2 + scale_x_continuous(name = "MIC (mg/L)",limits = c(-4.5, 8.5), breaks = seq(-4, 8), labels = xlab)

pa3 = pa3 + geom_vline(xintercept= (log2(1)), colour = "red", linetype = "dashed")
pa3 = pa3 + coord_fixed(0.8)
subt = expression(paste("with breakpoint for ", italic("C.glabrata")))
pa3 = pa3 + labs(title = "Amphotericin B", subtitle = subt)
pa3 = pa3 + theme(plot.margin = unit(c(0.5,0.25,0.5,0.5), "cm"),
                  plot.title = element_text(hjust = 0, size = 30),
                  plot.subtitle=element_text(size=20, hjust=0,
                                            color="red"), 
                  axis.text.y = element_text(size = 15, face = "bold"), 
                  axis.title.x = element_text(size = 20, face = "bold"),
                  axis.text.x = element_text(angle = 45, hjust = 1, size = 15, face = "bold"))

print(pa3)


dev.off()
```

### size
```{r}
png('size.png',height = 550 , width = 500)

s = ggplot(mic) 
s = s +  geom_segment(aes(x=rep(log10(0.9), time(length(n))), 
                          y = row , xend=log10(n) ,
                          yend = row
                            ),size = 2, show.legend = F,
                      colour = "grey38") 

s2 = s + scale_y_continuous(name = "", breaks = 1:length(mic$n) ,labels = rep(c(""), times = length(mic$n)))  
s3 = s2 + scale_x_continuous(name = "Number of isolates",limits = c(log10(0.9), 2.6), breaks = log10(c(1,10,50,100, 200)), labels = c(1,10,50,100, 200) )

(1.6 * 5) / 32

s4 = s3 + coord_fixed(0.1)
s4 = s4 + labs(title = "Number of isolates")
s4 = s4 + theme(plot.margin = unit(c(0.5,0.25,0.5,0.5), "cm"),
                  plot.title = element_text(hjust = 0, size = 30),
                  plot.subtitle=element_text(size=20, hjust=0,
                                            color="red"), 
                  axis.text.y = element_text(size = 15, face = "bold"), 
                  axis.title.x = element_text(size = 20, face = "bold"),
                  axis.text.x = element_text(size = 15, face = "bold"))

print(s4)
dev.off()
```

### all together now

```{r}
library("gridExtra")
library("gtable")
library(ggplot2)
library("grid")
png('arrenged.png',height = 650 , width = 500)
grid.arrange(pf3, pc3,pa3,s3, nrow = 2 )
dev.off()

png('arrenged2.png',height = 550 , width = 600)
g1 <- ggplotGrob(pf3)
g2 <- ggplotGrob(pc3)
g <- cbind(g1, g2, size = "first")
g$heights = unit.pmax(g1$heights, g2$heights)
grid.newpage()
grid.draw(g)
dev.off()

png('arrenged3.png',height = 550 , width = 600)
g1 <- ggplotGrob(pa3)
g2 <- ggplotGrob(s4)
g <- cbind(g1, g2, size = "first")
g$heights = unit.pmax(g1$heights, g2$heights)
grid.newpage()
grid.draw(g)
dev.off()

png('arrenged3.png',height = 2480/2 , width = 3508/2)
g0 = ggplotGrob(pf3)
g00 <- ggplotGrob(pc3)
g1 <- ggplotGrob(p2a3)
g2 <- ggplotGrob(s4)
g <- cbind(g0, g00, g1, g2, size = "first")
g$heights = unit.pmax(g1$heights, g2$heights)
grid.newpage()
grid.draw(g)
dev.off()

10** 1.5
```

```{r}
#breakpoint glabrata = 1

p2a2 = pa + scale_y_continuous(name = "",breaks = 1:length(mic$n) ,labels = rep("", times = length(mic$n))) 
p2a3 = p2a2 + scale_x_continuous(name = "MIC (mg/L)",limits = c(-4.5, 8.5), breaks = seq(-4, 8), labels = xlab)

p2a3 = p2a3 + geom_vline(xintercept= (log2(1)), colour = "red", linetype = "dashed")
p2a3 = p2a3 + coord_fixed(0.8)
subt = expression(paste("with breakpoint for ", italic("C.glabrata")))
p2a3 = p2a3 + labs(title = "Amphotericin B", subtitle = subt)
p2a3 = p2a3 + theme(plot.margin = unit(c(0.5,0.25,0.5,0.5), "cm"),
                  plot.title = element_text(hjust = 0, size = 30),
                  plot.subtitle=element_text(size=20, hjust=0,
                                            color="red"), 
                  axis.text.y = element_text(size = 15, face = "bold"), 
                  axis.title.x = element_text(size = 20, face = "bold"),
                  axis.text.x = element_text(size = 15, angle = 45, hjust = 1, face = "bold"))

print(p2a3)


```