---
title: "Range plots"
author: "Léonard Jequier"
date: "21 novembre 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Data
```{r}
mic = read.csv("MIC4.csv", header = T, sep = ";")
names(mic)[1] = "Country"
summary(mic)
mic$Country[1:10]
```


### rearrenge data by date:
```{r}


mic$epi = paste( mic$Year, mic$Country, sep = "_")
mic = mic[order(mic$epi,decreasing=T, na.last = T),]
mic$row = seq(1:length(mic$Country))


mic = mic[seq(1, length(mic$Country)-2),]
mic$epi
```

### Fluco - Deal with missing data
```{r}
mic$FL_min = log2(mic$FL_min)
mic$FL_max = log2(mic$FL_max)
```

```{r}

for(i in seq(1:length(mic$Country))){
    print(mic$epi[i])
    print(mic$FL_min[i])
    print(mic$FL_max[i])
    
  if(!is.na(mic$FL_min[i]) & mic$FL_min[i] == mic$FL_max[i]) {
    mic$FL_min[i] = mic$FL_min[i] - 0.25
    mic$FL_max[i] = mic$FL_max[i] + 0.25
}
}


```

### Fluconazole - plot
```{r}
library("ggplot2")

xlab = 2 ** seq(-4,8)

par(mar=c(3,2,2,2))

pf = ggplot(mic) 

pf = pf +  geom_segment(aes(x=FL_min, 
                          y = row , xend=FL_max ,
                          yend = row),
                        show.legend = F,
                        size = 2,
                      colour = "cornflowerblue") 

pf2 = pf + scale_y_continuous(name = "",breaks = 1:length(mic$n) ,labels = as.character(mic$epi)) 

pf3 = pf2 + scale_x_continuous(name = "MIC (mg/L)",limits = c(-4.3, 8.3), breaks = seq(-4, 8), labels = xlab)

pf3 = pf3 + geom_vline(xintercept= (log2(32)), colour = "red", linetype = "dashed")
pf3 = pf3 + coord_fixed(0.8)
subt = expression(paste("Tentative breakpoint for ", italic("C.auris")))
pf3 = pf3 + labs(title = "Fluconazole", subtitle = subt)
pf3 = pf3 + theme(plot.margin = unit(c(0.5,0.25,0.5,0.5), "cm"),
                  plot.title = element_text(hjust = 0, size = 30),
                  plot.subtitle=element_text(size=20, hjust=0,
                                            color="red"), 
                  axis.text.y = element_text(size = 13, face = "bold"), 
                  axis.title.x = element_text(size = 20, face = "bold"),
                  axis.text.x = element_text(size = 12, angle = 45, hjust = 1, face = "bold"))

print(pf3)



```

### Casp - deal with NA
```{r}
mic$Casp_min = as.numeric(mic$Casp_min)
mic$Casp_max = as.numeric(mic$Casp_max)

mic$Casp_min = log2(mic$Casp_min)
mic$Casp_max = log2(mic$Casp_max)

mic$Casp_min == mic$Casp_max

for(i in seq(1:length(mic$Country))){
  if(!is.na(mic$Casp_min[i]) & mic$Casp_min[i] == mic$Casp_max[i]) {
    mic$Casp_min[i] = mic$Casp_min[i] - 0.25
    mic$Casp_max[i] = mic$Casp_max[i] + 0.25
    
}
}
```

### Caspo - plot 
```{r}
xlab2 = 2 ** seq(-6,5)


pc = ggplot(mic) 

pc = pc +  geom_segment(aes(x=Casp_min, 
                          y = row , xend=Casp_max ,
                          yend = row),
                          size = 2,
                        show.legend = F,
                      colour = "cornflowerblue") 

pc2 = pc + scale_y_continuous(name = "", breaks = 1:length(mic$n) ,labels = rep(c(""), times = length(mic$n))) 

pc3 = pc2 + scale_x_continuous(name = "MIC (mg/L)",limits = c(-6.3, 5.3), breaks = seq(-6, 5), labels = xlab2)

pc3 = pc3 + geom_vline(xintercept= (log2(2)), colour = "red", linetype = "dashed") 
pc3 = pc3 + coord_fixed(0.8)
subt = expression(paste(""))
pc3 = pc3 + labs(title = "Caspofungin", subtitle = subt)
pc3 = pc3 + theme(plot.margin = unit(c(0.5,0.25,0.5,0.5), "cm"),
                  plot.title = element_text(hjust = 0, size = 30),
                  plot.subtitle=element_text(size=20, hjust=0,
                                            color="red"), 
                  axis.text.y = element_text(size = 9, face = "bold"), 
                  axis.title.x = element_text(size = 20, face = "bold"),
                  axis.text.x = element_text(size = 12, angle = 45, hjust = 1, face = "bold"))



```

### AMB - deal with NA
```{r}
mic$AMB_min = as.numeric(mic$AMB_min)
mic$AMB_max = as.numeric(mic$AMB_max)

mic$AMB_min = log2(mic$AMB_min)
mic$AMB_max = log2(mic$AMB_max)

mic$AMB_min == mic$AMB_max

for(i in seq(1:length(mic$Country))){
  if(!is.na(mic$AMB_min[i]) & mic$AMB_min[i] == mic$AMB_max[i]) {
    mic$AMB_min[i] = mic$AMB_min[i] - 0.25
    mic$AMB_max[i] = mic$AMB_max[i] + 0.25
}
}
```

### AMB - plot 
```{r}

par(mar=c(3,2,2,2))
pa = ggplot(mic) 
pa = pa +  geom_segment(aes(x=AMB_min, 
                          y = row , xend=AMB_max ,
                          yend = row),
                           size = 2,
                        show.legend = F,
                      colour = "cornflowerblue")

pa2 = pa + scale_y_continuous(name = "",breaks = 1:length(mic$n) ,labels = rep("", times = length(mic$n))) 
pa3 = pa2 + scale_x_continuous(name = "MIC (mg/L)",limits = c(-4.3, 8.3), breaks = seq(-4, 8), labels = xlab)

pa3 = pa3 + geom_vline(xintercept= (log2(2)), colour = "red", linetype = "dashed")
pa3 = pa3 + coord_fixed(0.8)
subt = expression(paste(""))
pa3 = pa3 + labs(title = "Amphotericin B", subtitle = subt)
pa3 = pa3 + theme(plot.margin = unit(c(0.5,0.25,0.5,0.5), "cm"),
                  plot.title = element_text(hjust = 0, size = 30),
                  plot.subtitle=element_text(size=20, hjust=0,
                                            color="red"), 
                  axis.text.y = element_text(size = 15, face = "bold"), 
                  axis.title.x = element_text(size = 20, face = "bold"),
                  axis.text.x = element_text(size = 12, angle = 45, hjust = 1, face = "bold"))


```

### size
```{r}

s = ggplot(mic) 
s = s +  geom_segment(aes(x=rep(log10(0.9), time(length(n))), 
                          y = row , xend=log10(n) ,
                          yend = row
                            ),size = 2, show.legend = F,
                      colour = "grey38") 

s2 = s + scale_y_continuous(position="right",name = "", breaks = 1:length(mic$n) ,labels = mic$auth)  
s3 = s2 + scale_x_continuous(name = "Number of isolates",limits = c(log10(0.9), 2.6), breaks = log10(c(1,10,50,100, 200)), labels = c(1,10,50,100, 200) )


s4 = s3 + coord_fixed(0.1)
s4 = s4 + labs(title = "Number of isolates")
s4 = s4 + theme(plot.margin = unit(c(0.5,0.25,0.5,0.5), "cm"),
                  plot.title = element_text(hjust = 0, size = 30),
                  plot.subtitle=element_text(size=20, hjust=0,
                                            color="red"), 
                  axis.text.y = element_text(size = 13, face = "bold"), 
                  axis.title.x = element_text(size = 20, face = "bold"),
                  axis.text.x = element_text(size = 12,angle = 45, hjust = 1, face = "bold"))

png('number.png',height = 550 , width = 500)
print(s4)
dev.off()
```

### all together now

```{r}
library("gridExtra")
library("gtable")
library(ggplot2)
library("grid")


png('arrenged_final.png',height = 2480/2 , width = 3508/2)
g0 = ggplotGrob(pf3)
g00 <- ggplotGrob(pc3)
g1 <- ggplotGrob(pa3)
g2 <- ggplotGrob(s4)
g <- cbind(g0, g1, g00, g2, size = "first")
g$heights = unit.pmax(g1$heights, g2$heights)
grid.newpage()
grid.draw(g)
dev.off()

tiff('arrenged_final.tiff',height = 50 , width = 50,units = 'cm',compression ="lzw",res=300)
g0 = ggplotGrob(pf3)
g00 <- ggplotGrob(pc3)
g1 <- ggplotGrob(pa3)
g2 <- ggplotGrob(s4)
g <- cbind(g0, g1, g00, g2, size = "first")
g$heights = unit.pmax(g1$heights, g2$heights)
grid.newpage()
grid.draw(g)
dev.off()

```

